name: Regenerate client
on:
  repository_dispatch:
    types: [regenerate]
jobs:
  build:
    name: Generate API client
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: EmesaDEV/partner-platform-api-client-php
      - run: cp composer.json composer_backup.json && cp README.md README_backup.md && cp git_push.sh git_push_backup.sh
      - run: sleep 1 && START_DATE_TIME=$(echo $(date -R)) && docker run --rm -v ${PWD}:/${PWD} swaggerapi/swagger-codegen-cli-v3:3.0.30 generate -i https://market.emesa.org/supplier-api/v1/doc.json -DinvokerPackage=Emesa\\PartnerPlatform,apiTests=false,modelTests=false,modelDocs=false --http-user-agent Emesa-Supplier-Api-Client/PHP/${{ github.event.client_payload.release_note }} -l php -o ${PWD}/ && cp -a SwaggerClient-php/. ${PWD} && mv composer_backup.json composer.json && mv README_backup.md README.md && mv git_push_backup.sh git_push.sh && find . -not -newermt "$START_DATE_TIME" -not -path "./.git*" -not -name "git_push.sh" -not -name "README.md" -not -name "composer.json"> filesToRemove.txt
      - run: cat filesToRemove.txt | xargs git rm -r | true
      - run: git config --global user.email "dmitry.semenkov@emesa.nl"
      - run: git config --global user.name "Github action"
      - run: git diff
      - run: git add -- . :!SwaggerClient-php/* :!.swagger-codegen-ignore :!.swagger-codegen/* :!filesToRemove.txt
      - run: git status
      - run: git commit -m"${{ github.event.client_payload.release_note }}"
      - run: git log
      - run: git tag "${{ github.event.client_payload.release_note }}"
      - run: git tag -n
      - run: git push origin master
      - run: git push origin --tags
